In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error,root_mean_squared_error,r2_score

In [2]:
data=pd.read_csv('California_updated.csv')
X=data.drop('MedHouseVal',axis=1)
y=data['MedHouseVal']
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=1234)
lr=LinearRegression()
lr.fit(X_train,y_train)
y_pred=lr.predict(X_test)

MSE=mean_squared_error(y_test,y_pred)
RMSE=root_mean_squared_error(y_test,y_pred)
R2=r2_score(y_test,y_pred)

In [3]:
print('MSE',MSE)
print('RMSE',RMSE)
print('R2',R2)

MSE 0.6676008481118304
RMSE 0.8170684476295914
R2 0.5065090715994581


**Model Save**

- We can save model in two ways

    - suning pickle : .pki

    - using joblib : .joblib

**pickle**

In [4]:
import pickle

- dump

    - we will save the model in .pkl format

    - it expexts the model and location

    - it is similar to file open write format

    - hear also will open the file with write bytes format

- load

   - similar way it needs only file name in read bytes format

In [5]:
# our model variable name is : lr
# where i want to save : same directory
# on what name i want to save: california
# on what extension i want to save : ,pkl
# file name : california,pkl
# write format is : wb

file=open('dummy.txt','w')
str1='hello'
file.write(str1)

5

In [6]:
str1='hello'
with open('dummy1.txt','w')as file:
    file.write(str1)

In [7]:
with open('california.pkl','wb') as file:
    pickle.dump(lr,file)

In [8]:
with open('california.pkl','rb') as file:
    loaded_model=pickle.load(file)

In [9]:
loaded_model

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


**real time prediction**

- how many values we need to pass

- the model developed by using 6 columns

- when im passing single list 1D

- model expects 2D data

- because 2D data gives flexible to process multiple qns at a time

    - is called as **Batch process**

In [10]:
loaded_model.predict([10,20,30,40,50,60])

C:\Users\shreyansh tiwari\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


ValueError: Expected 2D array, got 1D array instead:
array=[10 20 30 40 50 60].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [11]:
loaded_model.predict([[10,20,30,40,50,60]])

C:\Users\shreyansh tiwari\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([4.805776])

**batch process**

In [12]:
qn1=[10,20,30,40,50,60]
qn2=[1,2,3,4,5,6]
qns=[qn1,qn2]
qns=[[10,20,30,40,50,60],
     [1,2,3,4,5,6]]
loaded_model.predict(qns)

C:\Users\shreyansh tiwari\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([4.805776  , 2.33859314])

In [13]:
X_test.values

array([[-0.09973335,  1.85618152, -0.71657708, -0.1295939 , -0.23470435,
         1.01041149],
       [ 0.88522503,  1.85618152,  0.36781217, -0.00959844,  0.2829428 ,
        -0.69846949],
       [ 0.00227869,  1.22051689, -0.7633789 , -0.12996558, -0.27878108,
         1.00572963],
       ...,
       [-0.69954101,  0.10810379, -1.04507285, -0.04511012, -0.13862674,
         1.11341254],
       [ 0.00227869,  1.85618152, -0.9179132 , -0.1134721 , -0.42105787,
         1.04786642],
       [-0.06088666, -1.08376738, -0.36600499,  0.0038624 , -0.02664503,
         0.55158865]], shape=(4128, 6))

In [14]:
X_test.values[0]

array([-0.09973335,  1.85618152, -0.71657708, -0.1295939 , -0.23470435,
        1.01041149])

In [15]:
loaded_model.predict(X_test.values[0])

C:\Users\shreyansh tiwari\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


ValueError: Expected 2D array, got 1D array instead:
array=[-0.09973335  1.85618152 -0.71657708 -0.1295939  -0.23470435  1.01041149].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [16]:
# generally model we will save because
# clinet side ppl will use
# how many columns 

In [17]:
dict1={'model':lr,
      'columns':X_train.columns,
      'num_of_columns':len(X_train.columns)}

In [18]:
with open('californial.pkl','wb')as file:
    pickle.dump(dict1,file)

In [19]:
with open('californial.pkl','rb')as file:
    loaded_model1=pickle.load(file)

In [20]:
loaded_model1

{'model': LinearRegression(),
 'columns': Index(['MedInc', 'HouseAge', 'Population', 'AveOccup', 'AveRooms', 'Latitude'], dtype='object'),
 'num_of_columns': 6}

In [21]:
MODEL=loaded_model1['model']
MODEL.predict([[1,2,3,4,5,6]])

C:\Users\shreyansh tiwari\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([2.33859314])

**Joblib**

- dump

- load

In [22]:
# file=open('california.pkl','wb')
#            |
# file='california.joblib'

# pickle.dump(lr,file)
# joblib.dump(lr,file)

In [23]:
# file=open('california.pkl','rb')
#            |
# file='california.joblib'

# pickle.load(file)
# joblib.load(file)

In [24]:
import joblib
file_path='california.joblib'
joblib.dump(lr,file_path)

['california.joblib']

In [25]:
file_path='california.joblib'
loaded_model2=joblib.load(file_path)

In [26]:
loaded_model2

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [27]:
loaded_model2.predict([[1,2,3,4,5,6]])

C:\Users\shreyansh tiwari\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([2.33859314])

In [28]:
dict1={'model':lr,
       'columns':X_train.columns,
      'num_of_columns':len(X_train.columns)}
file_path='california1.joblib'
joblib.dump(dict1,file_path)

['california1.joblib']

In [29]:
file_path='california1.joblib'
loaded_model3=joblib.load(file_path)

In [30]:
loaded_model3['model']

,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",True
,"copy_X copy_X: bool, default=TrueIf True, X will be copied; else, it may be overwritten.",True
,"tol tol: float, default=1e-6The precision of the solution (`coef_`) is determined by `tol` whichspecifies a different convergence criterion for the `lsqr` solver.`tol` is set as `atol` and `btol` of :func:`scipy.sparse.linalg.lsqr` whenfitting on sparse training data. This parameter has no effect when fittingon dense data... versionadded:: 1.7",1e-06
,"n_jobs n_jobs: int, default=NoneThe number of jobs to use for the computation. This will only providespeedup in case of sufficiently large problems, that is if firstly`n_targets > 1` and secondly `X` is sparse or if `positive` is setto `True`. ``None`` means 1 unless in a:obj:`joblib.parallel_backend` context. ``-1`` means using allprocessors. See :term:`Glossary ` for more details.",None
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive. Thisoption is only supported for dense arrays.For a comparison between a linear regression model with positive constraintson the regression coefficients and a linear regression without such constraints,see :ref:`sphx_glr_auto_examples_linear_model_plot_nnls.py`... versionadded:: 0.24",False


In [31]:
loaded_model3['model'].predict([[1,2,3,4,5,6]])

C:\Users\shreyansh tiwari\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([2.33859314])

# JOBLIB IS MAINLY USED FOR SKLEARN MODELS FAST AND BEST COMPARE TO .PKL